<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/Copy_of_Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = int(input('Enter No. of rows in the matrix : '))
b = int(input('Enter No. of columns in the matrix : '))
ran_array = np.random.random((a,b))
print(ran_array)
print('Average of all elements in the matrix is : ', np.mean(ran_array))

Enter No. of rows in the matrix : 5
Enter No. of columns in the matrix : 3
[[0.62878887 0.24869939 0.7117161 ]
 [0.97214631 0.34370151 0.27461354]
 [0.44967749 0.03227039 0.61118709]
 [0.30500154 0.58863933 0.56480025]
 [0.31605349 0.06347368 0.97801209]]
Average of all elements in the matrix is :  0.4725854052205488


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
a = 6
b = 8
array_code = np.ones((a,b), dtype=int)
array_code[1:-1,1:-1] = 0                 # In indexing,Start from 0, 1 is Included and -1 is Excluded.
print(array_code)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
import numpy as np
a = int(input('Enter No. of rows in the matrix : '))
b = int(input('Enter No. of columns in the matrix : '))

def create_border_array(shape):
  array = np.ones((shape), dtype=int)
  array[1:-1, 1:-1] = 0
  return array

border_array = create_border_array((a,b))
print(border_array)

Enter No. of rows in the matrix : 7
Enter No. of columns in the matrix : 9
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
vector1 = np.random.random(10)
print(vector1)


# In this example, np.linspace(0, 1, 12, endpoint=False) generates an array
# of 12 equally spaced values from 0 to 1 (both included), and then [1:-1]
# is used to exclude the first and last elements, resulting in a vector of
# size 10 with values ranging from 0 to 1 (both excluded).
vector2 = np.linspace(0, 1, 12, endpoint=False)[1:-1]
print(vector2)

[0.24276295 0.74047656 0.36885485 0.89083912 0.84985233 0.85591586
 0.23573392 0.74570074 0.51233083 0.41711766]
[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
# Identity matrix are always square matrix (ie the no of rows and columns have to be same).
# So you cannot have an identiry matrix of shape (3,4)
#To create an identity matrix of shape (3,3)
a1 = np.eye(3,3)
print(a1)

# In case you try to get Identity matrix of shape (3,4), it will look like this
a2 = np.eye(3,4)
print(a2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
a1 = np.ones((5,5), dtype=int)
for i in range(0,5):
  a1[i]  = i
print(a1)


[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here

# Array with shape (6,7,8) will be a 6D array with 7 Rows and 8 Columns.
# Total elements will be 6x7x8 = 336.

import numpy as np
a1  = np.arange(336).reshape(6,7,8)
print(a1)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [ ]:
import numpy as np

# Step 1: Import the Numpy library
# Already assuming you have Numpy installed. If not, you can install it using: pip install numpy

# Step 2: Define the shape of the array
shape = (6, 7, 8)

# Step 3: Find the index of the 100th element
index_100th_element = np.unravel_index(99, shape)

# Step 4: Print the result
print("Index of the 100th element:", index_100th_element)


Index of the 100th element: (1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
import numpy as np
# Let the Input Numbers given be in form of a string
str = '1 2 3 4 -8 -10'
print(str)

array = np.fromstring(str, sep = ' ')
print(array[::-1])                    # To print in reverse order use [::-1]


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here

a1 = np.array([])
print(a1)
count = 0
for i in a1:
  count = count + 1
print('element count = ', count)

a2 = np.array([1,2])
count= 0
print(a2)
for i in a2:
  count = count+1
print('element count = ', count)



[]
element count =  0
[1 2]
element count =  2


In [ ]:
a3 = np.arange(40).reshape(5,8)
print(a3)

count = 0
for i in np.nditer(a3):
  count = count + 1
print('element count is ', count)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
element count is  40


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

a = np.array([[0 1 2 3 4], [5 6 7 8 9]])
b = np.array([[1 1 1 1 1], [1 1 1 1 1]])
print(a)

SyntaxError: ignored

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
import numpy as np

def subtract_row_mean(matrix):
    """
    Subtract the mean of each row from a matrix.

    Parameters:
    - matrix: Numpy array.

    Returns:
    - Numpy array with row means subtracted.
    """
    # Calculate the mean of each row
    row_means = np.mean(matrix, axis=1, keepdims=True)
    print(row_means)

    # Subtract the row means from the original matrix
    result_matrix = matrix - row_means

    return result_matrix

# Example usage:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result = subtract_row_mean(matrix)

# Print the result
print(result)


[[2.]
 [5.]
 [8.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


\###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix[:,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
import numpy as np

def sorted_array_highest(arr,n):
  sorted_arr = np.sort(arr)
  return sorted_arr[n]

a1 = np.array([12,34,40,7,1,0])
a2 = np.array([34,67,10,8,5,89])
n1 = 3
n2 = 0

result1 = sorted_array_highest(a1,n1)
result2 = sorted_array_highest(a2,n2)

print(result1)
print(result2)


12
5


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
import numpy as np

a = np.array([1,2,3])
b = np.transpose(np.vstack((a,a,a)))
c = np.vstack((a,a,a))
d = np.vstack((b,c))

d.ravel()


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])