<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/Numpy_100_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 Numpy Problems

##### This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

001 - Import Numpy package under the name np

In [71]:
import numpy as np

002 - Print the Numpy version

In [72]:
print(np.__version__)

1.23.5


003 - Create a Null Vector of size 10

In [73]:
a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


004 - Find the Memory Size, No of Dimension, Total Elements, Element size in bytes for an array

In [74]:
a1 = np.zeros(12, np.int64).reshape(2,2,3)  # Here we use integer 64
print(a1)
print('No of dimensions of the array is ', a1.ndim)
print('Total no of elements in array is ', a1.size)
print('Size of each element in bytes is ', a1.itemsize, ' bytes')
print('No. of Bytes used by Array is', (a1.size)*(a1.itemsize), 'bytes')

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
No of dimensions of the array is  3
Total no of elements in array is  12
Size of each element in bytes is  8  bytes
No. of Bytes used by Array is 96 bytes


004 - Create a null vector of size 10 but the fifth element must be 1

In [75]:
a1 = np.zeros(10)
a1[5] = 1
print(a1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


005 - Create a vector whose element values range from 10 to 49

In [76]:
a1 = np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


006 - Reverse a vector i.e. first element becomes last and vice versa

In [77]:
a1 = np.arange(10)
print(a1)
a2 = a1[::-1]
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


007 - Create a 3x3 matrix with values ranging from 0 to 8

In [78]:
a1 = np.arange(9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


008 - Find indices of non zero elements from [1,2,0,0,4,0]

In [79]:
import numpy as np

a1 = np.array([1,2,0,0,4,0])    # We have non zero elements in index 0,1 and 4
a2 = np.nonzero(a1)
print(a2)

(array([0, 1, 4]),)


009 - Create a 3x3 identity matrix

In [80]:
a1 = np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


010 - Create a 3x3x3 array with random values

In [81]:
a1 = np.random.random((3,3,3))
print(a1)

[[[0.6296819  0.56307163 0.04847118]
  [0.93118141 0.20559255 0.74779567]
  [0.41952002 0.96580061 0.18369919]]

 [[0.73288752 0.44595369 0.75991907]
  [0.8407923  0.90337974 0.8860133 ]
  [0.02920231 0.70164247 0.93826697]]

 [[0.14134776 0.3237414  0.79344351]
  [0.96759059 0.78059996 0.95365645]
  [0.5862195  0.90058082 0.79452501]]]


011 - Create a 10x10 array with random values and find the minimum and maximum values

In [82]:
a1 = np.random.random((10,10))*10
print(a1)
print('Value of the smallest element is', a1.min())
print('Value of the largest element is', a1.max())

[[1.48012538 7.1788058  8.31285102 1.96484796 1.52927257 3.82616159
  6.1765283  9.39348267 9.95836052 4.89676165]
 [9.15112999 7.86578466 9.97290261 4.68020554 1.89987764 8.38015331
  6.14170208 6.66939514 6.78343913 1.34584101]
 [9.79607659 9.61319957 0.68652109 5.7472648  0.36532924 1.31065634
  9.60900683 8.20771709 8.86557717 3.93184374]
 [1.83520535 8.97829764 6.11488653 9.54603676 3.05206153 3.77528292
  8.18125278 6.48567198 1.00764124 3.93060487]
 [2.32583435 9.04683766 5.65802136 3.42381015 3.45184225 0.02483265
  0.88934879 1.83516106 1.7057627  9.75778939]
 [3.97065796 5.96674107 5.8602019  1.0325446  9.66651631 7.77049283
  0.65481187 2.63039307 9.86627129 4.6797607 ]
 [8.1388358  7.98408395 9.24503035 3.03059736 0.97092798 1.90485285
  5.74543067 6.58606774 9.93139232 2.7465134 ]
 [5.93641795 1.52062217 8.64991715 8.32018436 2.23007067 9.17610096
  6.287203   2.3037836  9.66887949 3.62561891]
 [6.7532929  8.63334456 0.62952729 4.15709464 1.27154179 2.19451353
  3.63821096

012 - Create a random vector of size 30 and find the mean value


In [83]:
a1 = np.random.random(30)
print(a1)
print('The Mean of all the elements is', a1.mean())

[0.88548248 0.26020222 0.6929435  0.72448532 0.05609623 0.44593249
 0.03648467 0.39623596 0.90902506 0.82720917 0.16823629 0.4275945
 0.93217442 0.80879842 0.60614686 0.52568054 0.29102175 0.57104628
 0.00366507 0.43240818 0.40533574 0.9386247  0.00844704 0.27072297
 0.55129434 0.00949871 0.09779103 0.58830919 0.98992869 0.83651254]
The Mean of all the elements is 0.48991114599625324


013 - Create a 2D array with 1 on the border and 0 inside

In [84]:
a1 = np.ones((7,7))
a1[1:-1,1:-1] = 0       # We use indexing. 1 is INCLUSIVE and -1 is EXCLUDED
print(a1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


014 - Add a border with all 0's around a existing array

In [85]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a1 = np.pad(a1, pad_width=1, constant_values=0)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


015 - What is the result of following expressions?

In [86]:
a1 = np.nan
print(a1*0)
print(np.nan == np.nan)
a2 = np.inf
print(a2)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.inf - np.inf)
print(0.1 * 3)
print(0.3 == 0.1*3)
print(np.nan in set([np.nan]))

nan
False
inf
False
nan
nan
0.30000000000000004
False
True


016 - Show how np.diag works

In [87]:
x = np.arange(25).reshape(5,5)      # It is a 5x5 Square Matrix
print(x, end='\n\n')                # end='\n\n' is used just to have additional blank line
print(np.diag(x))                   # Used to Extract elements in Diagonal of Matrix x
print(np.diag(x, k=1))              # Used to extract elements ONE layer ABOVE Diagonal line
print(np.diag(x, k=2))              # Used to extract elements TWO layer ABOVE Diagonal line
print(np.diag(x, k=-1))             # Used to extract elements ONE layer BELOW Diagonal line
print(np.diag(x, k=-2))             # Used to extract elements TWO layer BELOW Diagonal line

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]
[ 1  7 13 19]
[ 2  8 14]
[ 5 11 17 23]
[10 16 22]


017 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [88]:
z = np.diag(1+np.arange(4),k=-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


018 - Some more examples of np.diag() use cases

In [89]:
z = np.arange((5))
print(z)

print()
z = np.diag(np.arange(5))
print(z)
print()

z = np.diag(1+np.arange(4))
print(z)
print()

z = np.diag(1+np.arange(4), k=-1) # Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
print(z)

[0 1 2 3 4]

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


019 - Create a 8x8 matrix and fill it with a checkerboard pattern

In [90]:
a1 = np.zeros(64, np.int8).reshape(8,8)

a1[1::2, ::2 ] = 1    # Fill 1 in all alternate rows from 1st to last & alternate columns from 0th to last
a1[ ::2,1::2 ] = 1    # Fill 1 in all alternate rows from 0th to last & alternate columns from 1st to last
print(a1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


020 - Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [91]:
print(np.arange(10).reshape(1,10))
print('Index value of 4th element is ', end='')
print(np.unravel_index(4,(10)))     # For a 1D array with elements from 0 to 9
                                    # Index value for element'4' will also be 4
print()

print(np.arange(9).reshape(3,3))
print('Index value of 5th element is ', end='')
print(np.unravel_index(5,(3,3)))     # For a 2D array with elements from 0 to 9
                                    # Index value for element'5' will be(1,2)
print()
print(np.arange(336).reshape(6,7,8))
print('Index value of 100th element is ', end='')
print(np.unravel_index(100,(6,7,8)))


[[0 1 2 3 4 5 6 7 8 9]]
Index value of 4th element is (4,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Index value of 5th element is (1, 2)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [1

020 - Alternate Method for above problem No 018

In [92]:
a1 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


021 - Use of random() function, two use cases

In [95]:
a1 = np.random.random(25).reshape(5,5)
print(a1)
a2 = np.random.random((5,5))
print(a2)

[[0.54453571 0.78445519 0.40522477 0.40646313 0.31850563]
 [0.78640327 0.68521997 0.79159047 0.13892111 0.98907926]
 [0.90684444 0.86771849 0.58283894 0.0431445  0.97048313]
 [0.05770519 0.88749086 0.94949587 0.46889691 0.48701962]
 [0.07734351 0.40322242 0.51844308 0.43049142 0.66869142]]
[[0.27052394 0.19666307 0.83859032 0.47848726 0.77552426]
 [0.0700946  0.31618174 0.44023736 0.78727772 0.56319011]
 [0.242159   0.70514216 0.15550238 0.34427701 0.88209299]
 [0.93884761 0.08519592 0.20673827 0.11954237 0.49464207]
 [0.74481455 0.30497339 0.41809754 0.34477797 0.30029634]]


022 - Normalize a 5x5 random matrix

The data can be normalized by subtracting the mean (µ) of each feature and a division by the standard deviation (σ). This way, each feature has a mean of 0 and a standard deviation of 1. This results in faster convergence.

Calculate the mean and standard deviation of your dataset

https://towardsdatascience.com/how-to-calculate-the-mean-and-standard-deviation-normalizing-datasets-in-pytorch-704bd7d05f4c#:~:text=The%20data%20can%20be%20normalized,channel%20is%20normalized%20this%20way.

In [99]:
a1 = np.random.random((5,5))
print(a1)
print()
a1 = (a1 - np.mean (a1)) / (np.std (a1))  # Formula to Normaliza two parameters
print(a1)

[[0.96499837 0.18538277 0.04052371 0.53348718 0.22038032]
 [0.82095998 0.14529101 0.0358224  0.96478869 0.75102871]
 [0.90420668 0.21043096 0.25841124 0.05120828 0.73232383]
 [0.63145291 0.95277672 0.05663866 0.7813056  0.55920921]
 [0.30615197 0.62472459 0.97559844 0.02466845 0.65894626]]

[[ 1.37303475 -0.90755415 -1.33130652  0.11074649 -0.80517674]
 [ 0.95168306 -1.02483349 -1.34505914  1.37242137  0.74711495]
 [ 1.19520242 -0.83428134 -0.69392589 -1.30005124  0.69239806]
 [ 0.39732303  1.33728308 -1.28416589  0.83568314  0.18599044]
 [-0.55427119  0.37764085  1.40404284 -1.37768749  0.47774859]]


023 -