<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/Numpy_100_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 Numpy Problems

##### This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

001 - Import Numpy package under the name np

In [2]:
import numpy as np

002 - Print the Numpy version

In [3]:
print(np.__version__)

1.23.5


003 - Create a Null Vector of size 10

In [4]:
a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


004 - Find the Memory Size, No of Dimension, Total Elements, Element size in bytes for an array

In [5]:
a1 = np.zeros(12, np.int64).reshape(2,2,3)  # Here we use integer 64
print(a1)
print('No of dimensions of the array is ', a1.ndim)
print('Total no of elements in array is ', a1.size)
print('Size of each element in bytes is ', a1.itemsize, ' bytes')
print('No. of Bytes used by Array is', (a1.size)*(a1.itemsize), 'bytes')

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
No of dimensions of the array is  3
Total no of elements in array is  12
Size of each element in bytes is  8  bytes
No. of Bytes used by Array is 96 bytes


004 - Create a null vector of size 10 but the fifth element must be 1

In [6]:
a1 = np.zeros(10)
a1[5] = 1
print(a1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


005 - Create a vector whose element values range from 10 to 49

In [7]:
a1 = np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


006 - Reverse a vector i.e. first element becomes last and vice versa

In [8]:
a1 = np.arange(10)
print(a1)
a2 = a1[::-1]
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


007 - Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a1 = np.arange(9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


008 - Find indices of non zero elements from [1,2,0,0,4,0]

In [10]:
import numpy as np

a1 = np.array([1,2,0,0,4,0])    # We have non zero elements in index 0,1 and 4
a2 = np.nonzero(a1)
print(a2)

(array([0, 1, 4]),)


009 - Create a 3x3 identity matrix

In [11]:
a1 = np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


010 - Create a 3x3x3 array with random values

In [12]:
a1 = np.random.random((3,3,3))
print(a1)

[[[0.54195253 0.33165692 0.15760975]
  [0.5134513  0.95690305 0.743635  ]
  [0.66351429 0.97811627 0.67622363]]

 [[0.28508758 0.61124374 0.36342845]
  [0.25594407 0.64572287 0.6477013 ]
  [0.39734161 0.8525982  0.73511569]]

 [[0.71499818 0.32677316 0.02960012]
  [0.01479953 0.71935849 0.08647588]
  [0.39713839 0.85564181 0.34534996]]]


011 - Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
a1 = np.random.random((10,10))*10
print(a1)
print('Value of the smallest element is', a1.min())
print('Value of the largest element is', a1.max())

[[7.06843344 0.39270447 4.05431511 2.02290698 9.71547854 4.85550157
  6.18590277 1.57855168 3.77192885 7.41079315]
 [0.96981888 0.78700971 1.70010443 5.96550888 8.94720169 9.74946467
  3.07427931 9.51302785 4.8571673  0.79916801]
 [4.49394661 8.97015584 5.58444351 1.62973149 7.48379659 5.33395562
  3.2854062  0.01476431 1.14053986 4.9106502 ]
 [9.96539134 1.59725438 0.875136   5.69191846 6.35580942 0.89214946
  3.55959344 7.22850714 9.50936891 6.11818689]
 [7.36449797 0.90663144 7.51340184 4.85156936 8.24307181 8.38669885
  6.38962175 8.04920209 0.99723733 6.4123206 ]
 [9.76573734 6.98324764 9.62483429 5.38212585 8.20250724 2.61140342
  0.09148878 0.90386743 0.85386879 9.40494106]
 [2.62037959 4.6786546  2.11256337 9.38129083 9.70787689 6.70596065
  4.02338806 3.01625937 2.7106254  9.11724832]
 [3.34864683 0.39965896 6.3095408  6.94637635 2.94402815 0.23498631
  4.11369009 6.46076466 0.2740468  3.26907643]
 [8.79230778 1.05481353 4.88912506 2.06986789 8.46758885 1.21965573
  7.61489852

012 - Create a random vector of size 30 and find the mean value


In [14]:
a1 = np.random.random(30)
print(a1)
print('The Mean of all the elements is', a1.mean())

[0.73189426 0.18385556 0.56408135 0.33486906 0.20849292 0.82791392
 0.40076585 0.12982193 0.25001766 0.38653046 0.40795842 0.76266718
 0.96503902 0.46030899 0.45080892 0.95516187 0.50043674 0.37860834
 0.48359966 0.75726549 0.63742944 0.03918412 0.22350641 0.82777839
 0.580719   0.39768947 0.53007884 0.38557768 0.18080359 0.85856251]
The Mean of all the elements is 0.49338090161927917


013 - Create a 2D array with 1 on the border and 0 inside

In [15]:
a1 = np.ones((7,7))
a1[1:-1,1:-1] = 0       # We use indexing. 1 is INCLUSIVE and -1 is EXCLUDED
print(a1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


014 - Add a border with all 0's around a existing array

In [16]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a1 = np.pad(a1, pad_width=1, constant_values=0)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


015 - What is the result of following expressions?

In [17]:
a1 = np.nan
print(a1*0)
print(np.nan == np.nan)
a2 = np.inf
print(a2)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.inf - np.inf)
print(0.1 * 3)
print(0.3 == 0.1*3)
print(np.nan in set([np.nan]))

nan
False
inf
False
nan
nan
0.30000000000000004
False
True


016 - Show how np.diag works

In [18]:
x = np.arange(25).reshape(5,5)      # It is a 5x5 Square Matrix
print(x, end='\n\n')                # end='\n\n' is used just to have additional blank line
print(np.diag(x))                   # Used to Extract elements in Diagonal of Matrix x
print(np.diag(x, k=1))              # Used to extract elements ONE layer ABOVE Diagonal line
print(np.diag(x, k=2))              # Used to extract elements TWO layer ABOVE Diagonal line
print(np.diag(x, k=-1))             # Used to extract elements ONE layer BELOW Diagonal line
print(np.diag(x, k=-2))             # Used to extract elements TWO layer BELOW Diagonal line

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]
[ 1  7 13 19]
[ 2  8 14]
[ 5 11 17 23]
[10 16 22]


017 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [19]:
z = np.diag(1+np.arange(4),k=-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


018 - Some more examples of np.diag() use cases

In [20]:
z = np.arange((5))
print(z)

print()
z = np.diag(np.arange(5))
print(z)
print()

z = np.diag(1+np.arange(4))
print(z)
print()

z = np.diag(1+np.arange(4), k=-1) # Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
print(z)

[0 1 2 3 4]

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


019 - Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
a1 = np.zeros(64, np.int8).reshape(8,8)

a1[1::2, ::2 ] = 1    # Fill 1 in all alternate rows from 1st to last & alternate columns from 0th to last
a1[ ::2,1::2 ] = 1    # Fill 1 in all alternate rows from 0th to last & alternate columns from 1st to last
print(a1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


020 - Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
print(np.arange(10).reshape(1,10))
print('Index value of 4th element is ', end='')
print(np.unravel_index(4,(10)))     # For a 1D array with elements from 0 to 9
                                    # Index value for element'4' will also be 4
print()

print(np.arange(9).reshape(3,3))
print('Index value of 5th element is ', end='')
print(np.unravel_index(5,(3,3)))     # For a 2D array with elements from 0 to 9
                                    # Index value for element'5' will be(1,2)
print()
print(np.arange(336).reshape(6,7,8))
print('Index value of 100th element is ', end='')
print(np.unravel_index(100,(6,7,8)))


[[0 1 2 3 4 5 6 7 8 9]]
Index value of 4th element is (4,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Index value of 5th element is (1, 2)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [1

020 - Alternate Method for above problem No 018

In [23]:
a1 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


021 - Use of random() function, two use cases

In [24]:
a1 = np.random.random(25).reshape(5,5)
print(a1)
a2 = np.random.random((5,5))
print(a2)

[[0.27449682 0.23625081 0.55352019 0.6803992  0.18392256]
 [0.74330137 0.21686866 0.57507775 0.93425044 0.60386176]
 [0.24899441 0.95302331 0.37919919 0.66565395 0.02116757]
 [0.8332754  0.38034782 0.32983814 0.79700653 0.85198445]
 [0.87572735 0.23894941 0.44854043 0.75671601 0.33807924]]
[[0.58127411 0.33692759 0.83795138 0.40286561 0.45153069]
 [0.11330273 0.33194392 0.13566157 0.73811876 0.52992586]
 [0.28066291 0.86834505 0.63905691 0.39451481 0.7524965 ]
 [0.8130303  0.41166625 0.83216547 0.16634126 0.79428626]
 [0.45366148 0.1455554  0.89015884 0.30743199 0.67424964]]


022 - Normalize a 5x5 random matrix

The data can be normalized by subtracting the mean (µ) of each feature and a division by the standard deviation (σ). This way, each feature has a mean of 0 and a standard deviation of 1. This results in faster convergence.

Calculate the mean and standard deviation of your dataset

https://towardsdatascience.com/how-to-calculate-the-mean-and-standard-deviation-normalizing-datasets-in-pytorch-704bd7d05f4c#:~:text=The%20data%20can%20be%20normalized,channel%20is%20normalized%20this%20way.

In [25]:
a1 = np.random.random((5,5))
print(a1)
print()
a1 = (a1 - np.mean (a1)) / (np.std (a1))  # Formula to Normaliza two parameters
print(a1)

[[0.42909637 0.8973008  0.05262685 0.49536206 0.48241895]
 [0.11991795 0.3189215  0.69162127 0.20869742 0.59273287]
 [0.09296747 0.85413598 0.87991032 0.76567082 0.2612075 ]
 [0.74332196 0.62453251 0.13228391 0.74414946 0.68657642]
 [0.26861893 0.70467573 0.83956953 0.08533263 0.72161978]]

[[-0.28023341  1.38833068 -1.62187709 -0.04407897 -0.090205  ]
 [-1.38206837 -0.6728692   0.65534001 -1.0656804   0.30292637]
 [-1.47811317  1.23450201  1.32635535  0.91923418 -0.87854757]
 [ 0.83958843  0.41625236 -1.33799914  0.84253743  0.63736144]
 [-0.85213506  0.70186288  1.18259082 -1.50532184  0.76224725]]


023 - Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [27]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-27-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


024 - Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [36]:
a1 = np.arange(15).reshape(5,3)
a2 = np.arange(1,7).reshape(3,2)
print(a1)
print(a2)
np.dot(a1,a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[1 2]
 [3 4]
 [5 6]]


array([[ 13,  16],
       [ 40,  52],
       [ 67,  88],
       [ 94, 124],
       [121, 160]])

025 - Given a 1D array, negate all elements which are between 3 and 8, in place

In [41]:
a1 = np.array([1,6,0,5,3,6,23,12,5,7,9,4,1,40])
print(a1)
a1[(3<a1) & (a1<8)] *= -1
print(a1)

[ 1  6  0  5  3  6 23 12  5  7  9  4  1 40]
[ 1 -6  0 -5  3 -6 23 12 -5 -7  9 -4  1 40]


026 - What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
  

In [53]:
print(sum(range(5), -1))    # Using Pythons 'sum' function output should be 9
from numpy import *         # We are importing Numpy Libraries now
print(sum(range(5), -1))    # Using Numpy 'sum' function output should be 10

10
10


Using Python's built-in sum function:

print(sum(range(5), -1))

range(5) generates the numbers 0 to 4.and sum(range(5), -1) calculates the sum of the numbers in the range, and the second argument -1 is an initial value for the sum. In this case, it starts from -1 and adds the numbers in the range.
The output is the sum of the numbers in the range plus the initial value (-1), which is 9.

Using Numpy's sum function:

from numpy import *
print(sum(range(5), -1))

from numpy import * imports all functions and classes from the Numpy library.
sum(range(5), -1) calculates the sum of the numbers in the range using the Numpy sum function. The second argument -1 indicates the axis along which the sum is calculated. In this case, -1 means the last axis (axis 1 for a 1D array).
The output is the sum of the numbers in the range along the specified axis. The sum along axis 1 is [0+1+2+3+4], which is 10.

So, the final output of the three line code will be:
9
10






027 - How to find common values between two arrays?

In [57]:
a1 = np.random.randint(1,10,10)
print(a1)
a2 = np.random.randint(1,10,10)
print(a2)
print(np.intersect1d(a1,a2))      # Use Two Set Intersection theory

[8 9 2 1 7 2 8 4 3 6]
[5 5 9 2 8 1 3 2 4 2]
[1 2 3 4 8 9]


028 - Is the following expressions true?
      np.sqrt(-1) == np.emath.sqrt(-1)

In [58]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-58-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

The line of code np.sqrt(-1) == np.emath.sqrt(-1) will result in False. Let's break down the justification for this answer:

np.sqrt(-1):

Using np.sqrt (square root function from Numpy) on a negative number results in a complex number with a real part of 0 and an imaginary part of 1j. So, np.sqrt(-1) evaluates to 1j.
np.emath.sqrt(-1):

Using np.emath.sqrt (square root function from Numpy's emath module) on a negative number also results in a complex number. However, unlike np.sqrt, np.emath.sqrt returns a complex number with a real part of 0 and an imaginary part of 1j.
Therefore, np.sqrt(-1) == np.emath.sqrt(-1) is comparing a complex number (1j) with another complex number (1j), and the result is False. While these two complex numbers represent the same mathematical value, they are not considered equal by the == operator **due to potential floating-point precision differences.** For numerical comparisons, it's often better to check whether the difference is within a small tolerance rather than exact equality.

029 - How to get the dates of yesterday, today and tomorrow?

In [69]:
today = np.datetime64('today', 'D')
print(today)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
dayaftertomorrow = np.datetime64('today', 'D') + np.timedelta64(2, 'D')
print(dayaftertomorrow)

2023-12-07
2023-12-06
2023-12-09


030 - How to get all the dates corresponding to the month of Dec 2023?

In [74]:
a1 = np.arange('2023-12','2024-01', dtype ='datetime64[D]')
print(a1)

['2023-12-01' '2023-12-02' '2023-12-03' '2023-12-04' '2023-12-05'
 '2023-12-06' '2023-12-07' '2023-12-08' '2023-12-09' '2023-12-10'
 '2023-12-11' '2023-12-12' '2023-12-13' '2023-12-14' '2023-12-15'
 '2023-12-16' '2023-12-17' '2023-12-18' '2023-12-19' '2023-12-20'
 '2023-12-21' '2023-12-22' '2023-12-23' '2023-12-24' '2023-12-25'
 '2023-12-26' '2023-12-27' '2023-12-28' '2023-12-29' '2023-12-30'
 '2023-12-31']


031 - How to compute ((A+B)*(-A/2)) in place (without copy)? (

In [87]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])