<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/Numpy_100_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 Numpy Problems

#### This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

In [ ]:
# 001 - Import the numpy package under the name np

import numpy as np

In [ ]:
# 002 - Print the numpy version and the configuration

print(np.__version__)

1.23.5


In [ ]:
# 003 - Create a null vector of size 10

a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 004 - How to find the memory size of any array

a1 = np.zeros(12, np.int64).reshape(2,2,3)  # Here we use integer 64
print(a1)
print(a1.ndim)          # ndim gives number of dimension of the array
print(a1.size)          # size gives, total number of elements in the array
print(a1.itemsize)      # itemsize gives length of each element in array in bytes
print('No. of Bytes used by Array is', (a1.size)*(a1.itemsize), 'bytes')

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
3
12
8
No. of Bytes used by Array is 96 bytes


In [ ]:
# 004 - Create a null vector of size 10 but the fifth value which is 1

a1 = np.zeros(10)
a1[5] = 1
print(a1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# 007 - Create a vector with values ranging from 10 to 49

a1 = np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 008 - Reverse a vector (first element becomes last)

a1 = np.arange(10)
print(a1)
a2 = a1[::-1]
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# 009 - Create a 3x3 matrix with values ranging from 0 to 8

a1 = np.arange(9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 010 - Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

a1 = np.array([1,2,0,0,4,0])    # We have non zero elements in index 0,1 and 4
a2 = np.nonzero(a1)
print(a2)

(array([0, 1, 4]),)


In [5]:
# 011 - Create a 3x3 identity matrix

a1 = np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 012 - Create a 3x3x3 array with random values

a1 = np.random.random((3,3,3))
print(a1)

[[[0.59475275 0.8732491  0.44612193]
  [0.45218912 0.83123468 0.21463647]
  [0.50859518 0.25282459 0.85501484]]

 [[0.6873353  0.74064255 0.04394162]
  [0.01962473 0.62680539 0.03353737]
  [0.90063138 0.39398974 0.58650891]]

 [[0.25532416 0.83531776 0.73041297]
  [0.42106225 0.32881697 0.67859986]
  [0.88602371 0.30892979 0.49549656]]]


In [15]:
# 013 - Create a 10x10 array with random values and find the minimum and maximum values

a1 = np.random.random((10,10))*10
print(a1)
print('Value of the smallest element is', a1.min())
print('Value of the largest element is', a1.max())

[[7.6508425  3.11035235 0.85379942 9.70230885 4.21103858 3.68779171
  8.41643014 6.75938456 4.44272439 2.79587294]
 [3.55604871 7.14558782 0.88097834 1.7546001  2.86288689 3.49339402
  8.71900124 6.58019177 8.39909375 8.5953845 ]
 [7.92384941 7.53451204 1.11268581 2.55865041 2.08473567 6.72691679
  7.24663133 6.64248195 3.74343154 5.94241126]
 [6.29062782 2.19261458 7.33508452 8.89451635 6.15030643 5.04869894
  4.17482782 2.17747226 0.60835033 1.95400833]
 [2.42902843 2.25088967 5.42302323 7.61547969 0.64861004 3.25954156
  6.16456055 2.24303695 3.46833393 6.98626817]
 [6.58864195 4.61084568 3.46647127 4.70896695 8.01028225 7.73711321
  0.94982849 8.6868528  3.86602608 1.07080262]
 [4.09307374 5.23914222 0.35947602 7.48074198 3.20258234 0.0656915
  1.67748567 8.34990115 3.15904749 0.40821767]
 [7.34775585 1.75826688 3.37016158 3.09686318 6.98385434 7.77172387
  6.09370533 3.46977715 3.15380967 2.93609231]
 [8.77396085 5.53496723 6.20538166 2.22997683 1.50127606 8.37785759
  1.51574531 

In [19]:
# 014 - Create a random vector of size 30 and find the mean value

a1 = np.random.random(30)     # Create a vector of size 30 with values ranging from 1 to 100
print(a1)
print('The Mean of all the elements is', a1.mean())

[0.61981093 0.39691236 0.56970275 0.09967182 0.48252727 0.33099838
 0.19120447 0.27016253 0.98671561 0.88671493 0.97428523 0.80923024
 0.91770702 0.81346262 0.32878518 0.29781832 0.00578133 0.90158726
 0.72656018 0.87137655 0.80235885 0.70658627 0.90082942 0.80719484
 0.90914404 0.87408872 0.96698585 0.31684693 0.11152108 0.86770414]
The Mean of all the elements is 0.6248091704959005


In [25]:
# 015 -  Create a 2d array with 1 on the border and 0 inside

a1 = np.ones((7,7))
a1[1:-1,1:-1] = 0       # We use indexing. 1 is INCLUSIVE and -1 is EXCLUDED
print(a1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [37]:
# 016 - How to add a border (filled with 0's) around an existing array?

a1 = np.arange(1,10).reshape(3,3)
print(a1)
a1 = np.pad(a1, pad_width=1, constant_values=0)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [2]:
# 017 - What is the result of the following expression?
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [17]:
x = np.arange(25).reshape(5,5)      # It is a 5x5 Square Matrix
print(x, end='\n\n')                # end='\n\n' is used just to have additional blank line
print(np.diag(x))                   # Used to Extract elements in Diagonal of Matrix x
print(np.diag(x, k=1))              # Used to extract elements ONE layer ABOVE Diagonal line
print(np.diag(x, k=2))              # Used to extract elements TWO layer ABOVE Diagonal line
print(np.diag(x, k=-1))              # Used to extract elements ONE layer BELOW Diagonal line
print(np.diag(x, k=-2))              # Used to extract elements TWO layer BELOW Diagonal line

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 12 18 24]
[ 1  7 13 19]
[ 2  8 14]
[ 5 11 17 23]
[10 16 22]


In [18]:
# 018 - Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

z = np.diag(1+np.arange(4),k=-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
z = np.arange((5))
print(z)

print()
z = np.diag(np.arange(5))
print(z)
print()

z = np.diag(1+np.arange(4))
print(z)
print()

z = np.diag(1+np.arange(4), k=-1) # Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
print(z)

[0 1 2 3 4]

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [54]:
# 019 - Create a 8x8 matrix and fill it with a checkerboard pattern

a1 = np.zeros(64, np.int8).reshape(8,8)

a1[1::2,::2 ] = 1
a1[::2, 1::2] = 1
print(a1)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [65]:
# 020 - Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.arange(10).reshape(1,10))
print('Index value of 4th element is ', end='')
print(np.unravel_index(4,(10)))     # For a 1D array with elements from 0 to 9
                                    # Index value for element'4' will also be 4
print()

print(np.arange(9).reshape(3,3))
print('Index value of 5th element is ', end='')
print(np.unravel_index(5,(3,3)))     # For a 2D array with elements from 0 to 9
                                    # Index value for element'5' will be(1,2)
print()
print(np.arange(336).reshape(6,7,8))
print('Index value of 100th element is ', end='')
print(np.unravel_index(100,(6,7,8)))


[[0 1 2 3 4 5 6 7 8 9]]
Index value of 4th element is (4,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Index value of 5th element is (1, 2)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [1

In [69]:
# 020 - Create a checkerboard 8x8 matrix using the tile function

a1 = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
