<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/Numpy_100_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 Numpy Problems

#### This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation.

In [ ]:
# 001 - Import the numpy package under the name np

import numpy as np

In [ ]:
# 002 - Print the numpy version and the configuration

print(np.__version__)

1.23.5


In [ ]:
# 003 - Create a null vector of size 10

a1 = np.zeros(10)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 004 - How to find the memory size of any array

a1 = np.zeros(12, np.int64).reshape(2,2,3)  # Here we use integer 64
print(a1)
print(a1.ndim)          # ndim gives number of dimension of the array
print(a1.size)          # size gives, total number of elements in the array
print(a1.itemsize)      # itemsize gives length of each element in array in bytes
print('No. of Bytes used by Array is', (a1.size)*(a1.itemsize), 'bytes')

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
3
12
8
No. of Bytes used by Array is 96 bytes


In [ ]:
# 004 - Create a null vector of size 10 but the fifth value which is 1

a1 = np.zeros(10)
a1[5] = 1
print(a1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# 007 - Create a vector with values ranging from 10 to 49

a1 = np.arange(10,50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 008 - Reverse a vector (first element becomes last)

a1 = np.arange(10)
print(a1)
a2 = a1[::-1]
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# 009 - Create a 3x3 matrix with values ranging from 0 to 8

a1 = np.arange(9).reshape(3,3)
print(a1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 010 - Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np

a1 = np.array([1,2,0,0,4,0])    # We have non zero elements in index 0,1 and 4
a2 = np.nonzero(a1)
print(a2)

(array([0, 1, 4]),)


In [5]:
# 011 - Create a 3x3 identity matrix

a1 = np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 012 - Create a 3x3x3 array with random values

a1 = np.random.random((3,3,3))
print(a1)

[[[0.59475275 0.8732491  0.44612193]
  [0.45218912 0.83123468 0.21463647]
  [0.50859518 0.25282459 0.85501484]]

 [[0.6873353  0.74064255 0.04394162]
  [0.01962473 0.62680539 0.03353737]
  [0.90063138 0.39398974 0.58650891]]

 [[0.25532416 0.83531776 0.73041297]
  [0.42106225 0.32881697 0.67859986]
  [0.88602371 0.30892979 0.49549656]]]


In [15]:
# 013 - Create a 10x10 array with random values and find the minimum and maximum values

a1 = np.random.random((10,10))*10
print(a1)
print('Value of the smallest element is', a1.min())
print('Value of the largest element is', a1.max())

[[7.6508425  3.11035235 0.85379942 9.70230885 4.21103858 3.68779171
  8.41643014 6.75938456 4.44272439 2.79587294]
 [3.55604871 7.14558782 0.88097834 1.7546001  2.86288689 3.49339402
  8.71900124 6.58019177 8.39909375 8.5953845 ]
 [7.92384941 7.53451204 1.11268581 2.55865041 2.08473567 6.72691679
  7.24663133 6.64248195 3.74343154 5.94241126]
 [6.29062782 2.19261458 7.33508452 8.89451635 6.15030643 5.04869894
  4.17482782 2.17747226 0.60835033 1.95400833]
 [2.42902843 2.25088967 5.42302323 7.61547969 0.64861004 3.25954156
  6.16456055 2.24303695 3.46833393 6.98626817]
 [6.58864195 4.61084568 3.46647127 4.70896695 8.01028225 7.73711321
  0.94982849 8.6868528  3.86602608 1.07080262]
 [4.09307374 5.23914222 0.35947602 7.48074198 3.20258234 0.0656915
  1.67748567 8.34990115 3.15904749 0.40821767]
 [7.34775585 1.75826688 3.37016158 3.09686318 6.98385434 7.77172387
  6.09370533 3.46977715 3.15380967 2.93609231]
 [8.77396085 5.53496723 6.20538166 2.22997683 1.50127606 8.37785759
  1.51574531 

In [19]:
# 014 - Create a random vector of size 30 and find the mean value

a1 = np.random.random(30)     # Create a vector of size 30 with values ranging from 1 to 100
print(a1)
print('The Mean of all the elements is', a1.mean())

[0.61981093 0.39691236 0.56970275 0.09967182 0.48252727 0.33099838
 0.19120447 0.27016253 0.98671561 0.88671493 0.97428523 0.80923024
 0.91770702 0.81346262 0.32878518 0.29781832 0.00578133 0.90158726
 0.72656018 0.87137655 0.80235885 0.70658627 0.90082942 0.80719484
 0.90914404 0.87408872 0.96698585 0.31684693 0.11152108 0.86770414]
The Mean of all the elements is 0.6248091704959005


In [25]:
# 015 -  Create a 2d array with 1 on the border and 0 inside

a1 = np.ones((7,7))
a1[1:-1,1:-1] = 0       # We use indexing. 1 is INCLUSIVE and -1 is EXCLUDED
print(a1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [37]:
# 016 - How to add a border (filled with 0's) around an existing array?

a1 = np.arange(1,10).reshape(3,3)
print(a1)
a1 = np.pad(a1, pad_width=1, constant_values=0)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
