<a href="https://colab.research.google.com/github/VijayPune/DSMP1-Tasks/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [6]:
# code here
import numpy as np

a = np.random.randint(1,100,10)
b = np.random.randint(1,100,30).reshape(6,5)

In [7]:
a

array([97, 90, 41,  6, 81, 56, 74, 74, 92, 34])

In [8]:
b

array([[64, 97, 18, 86, 28],
       [41, 29, 75, 41, 11],
       [64, 31, 85, 83, 14],
       [11, 11,  3, 61, 75],
       [52, 81, 73, 19, 24],
       [96, 66, 62, 56, 66]])

In [21]:
# Sort Matrix a
print(np.sort(a))           # It is sorted in ascending order by default
print(np.sort(a)[::-1])     # To sort in descending order, that is max value first

[ 6 34 41 56 74 74 81 90 92 97]
[97 92 90 81 74 74 56 41 34  6]


In [22]:
# Sort Matrix b on column 2
print(np.sort(b,axis=1))    # By default the sort is in asceending order, min value first
print(np.sort(b,axis=1)[::-1])    # To sort in desceending order, max value first


[[18 28 64 86 97]
 [11 29 41 41 75]
 [14 31 64 83 85]
 [ 3 11 11 61 75]
 [19 24 52 73 81]
 [56 62 66 66 96]]
[[56 62 66 66 96]
 [19 24 52 73 81]
 [ 3 11 11 61 75]
 [14 31 64 83 85]
 [11 29 41 41 75]
 [18 28 64 86 97]]


In [19]:
# Sort Matrix b on rows
print(np.sort(b, axis=0))

[[11 11  3 19 11]
 [41 29 18 41 14]
 [52 31 62 56 24]
 [64 66 73 61 28]
 [64 81 75 83 66]
 [96 97 85 86 75]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [43]:
# code here
# Below is a matrix showing Marks for 5 students for 4 subjects
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]
# They have now marks declared for the 5th subject for all 5 students.
# Need to Add them to the marks matrix
extra_subject = [41, 87, 72, 36, 92]
new_marks = np.concatenate((marks,np.array([extra_subject]).T), axis=1)
print(new_marks)

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]


In [58]:
# Add one more column to each student showing their Total marks
total_marks = np.array(np.sum(new_marks, axis=1))
total_marks = np.concatenate((new_marks,np.array([total_marks]).T), axis=1)
print(total_marks)

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]]


In [72]:
# iv. Sort the array(non-ascending order) on total marks
# column--one added in above task. Show top 2 rows.

sort_total_marks = total_marks[total_marks[:,5].argsort()]
print(sort_total_marks)
print()
top_total_marks = np.flip(sort_total_marks, axis=0) # To Show Topper in total marks
print(top_total_marks)
print()
only_top_two_rows = top_total_marks[:2,:]   # To show only top 2 Total Marks
print(only_top_two_rows)

[[ 13  10   9  33  41 106]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 63  46  90  42  87 328]]

[[ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]

[[ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
# code here

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [65]:
# code here
a1 = np.random.randint(1,100,30).reshape(5,6)
print(a1)

[[65 46  1 74 78 23]
 [41 95 70 28 88 92]
 [84 85 23 42 59 71]
 [21 51 59 78 73 32]
 [35 60 88 66 44 22]]


In [66]:
print(np.flip(a1))        # To flip along both axes simultaneously

[[22 44 66 88 60 35]
 [32 73 78 59 51 21]
 [71 59 42 23 85 84]
 [92 88 28 70 95 41]
 [23 78 74  1 46 65]]


In [67]:
print(np.flip(a1,axis=0))   # To flip along Columns

[[35 60 88 66 44 22]
 [21 51 59 78 73 32]
 [84 85 23 42 59 71]
 [41 95 70 28 88 92]
 [65 46  1 74 78 23]]


In [68]:
print(np.flip(a1,axis=1))   # To flip on rows

[[23 78 74  1 46 65]
 [92 88 28 70 95 41]
 [71 59 42 23 85 84]
 [32 73 78 59 51 21]
 [22 44 66 88 60 35]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
# code here

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
# code here

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
# code here

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
# code here